### ISSUE TITLE
no viable alternative at input 'addresspayable'

### ISSUE THREAD

**Issue by limindlmu** [chicxurug/SolMet-Solidity-parser#6]
**command**: 
` java -jar .\target\SolMet-1.0-SNAPSHOT.jar -basePath F:\Project\code -outFile F:\Project\uo.csv`

When I run the above command and scan 0x054e84d7916537f7f68dbc25ab00f928932bc62b.sol (The file is shown below), I encountered the following error. 

**error**: 
line 24:16 no viable alternative at input 'addresspayable'
Parsing F:\Project\code\0x054e84d7916537f7f68dbc25ab00f928932bc62b\0x054e84d7916537f7f68dbc25ab00f928932bc62b.sol
Exception in thread "main" java.lang.NullPointerException
        at hu.sed.solmet.visitors.ContractVisitor.calculateDIT(ContractVisitor.java:84)
        at hu.sed.solmet.visitors.ContractVisitor.visitContractDefinition(ContractVisitor.java:67)
        at hu.sed.solmet.visitors.ContractVisitor.visitContractDefinition(ContractVisitor.java:20)
        at hu.sed.parser.antlr4.grammar.solidity.SolidityParser$ContractDefinitionContext.accept(SolidityParser.java:837)
        at org.antlr.v4.runtime.tree.AbstractParseTreeVisitor.visitChildren(AbstractParseTreeVisitor.java:46)
        at hu.sed.parser.antlr4.grammar.solidity.SolidityBaseVisitor.visitSourceUnit(SolidityBaseVisitor.java:20)
        at hu.sed.solmet.visitors.ContractVisitor.visitSourceUnit(ContractVisitor.java:43)
        at hu.sed.solmet.visitors.ContractVisitor.visitSourceUnit(ContractVisitor.java:20)
        at hu.sed.parser.antlr4.grammar.solidity.SolidityParser$SourceUnitContext.accept(SolidityParser.java:207)
        at org.antlr.v4.runtime.tree.AbstractParseTreeVisitor.visit(AbstractParseTreeVisitor.java:18)
        at hu.sed.solmet.main.Main.main(Main.java:91)   

** F:\Project\code\0x054e84d7916537f7f68dbc25ab00f928932bc62b\0x054e84d7916537f7f68dbc25ab00f928932bc62b.sol**
```sol
pragma solidity 0.5.8;

import "./PermissionService.sol";
import "./IRegulatorService.sol";

contract RegulatedToken is PermissionService {
    string public name = "SCI Equity Token";
    string public symbol = "SCI";
    uint8 public decimals = 8;
    string public CIK = "0001782615";

    IRegulatorService public regulatorService;

    event TokensRecovered(address _from, address _to, uint _amount);

    constructor(address _regulatorService) public {
        regulatorService = IRegulatorService(_regulatorService);
        _totalSupply = 0;
    }

    function replaceRegulatorService(address _newRegulatorService) public onlyReplaceRegulatorServicePermission {
        regulatorService = IRegulatorService(_newRegulatorService);
    }

    function changeSymbol(string memory _newSymbol) public onlyAttributesPermission {
        symbol = _newSymbol;
    }

    function changeCIK(string memory _newCIK) public onlyAttributesPermission {
        CIK = _newCIK;
    }

    function changename(string memory _newName) public onlyAttributesPermission {
        name = _newName;
    }

    function addWhitelisted(address _account, string memory _iso) public onlyAddWhitelistPermission {
        require(regulatorService.canAddToWhitelist(_account, _iso), "Regulator service is not allowed add this account to whitelist");
        super.addWhitelisted(_account, _iso);
    }

    function removeWhitelisted(address _account) public onlyRemoveWhitelistPermission {
        (bool _isWhitelistedAccount, string memory _iso) = isWhitelisted(_account);

        require(_isWhitelistedAccount, "Account is not whitelisted");
        require(regulatorService.canRemoveFromWhitelist(_account, _iso), "Regulator service is not allowed remove this account from whitelist");

        super.removeWhitelisted(_account);
    }

    function transfer(address _to, uint _amount) public onlyUnlocked returns(bool) {
        (bool _isWhitelistedFrom, string memory _isoFrom) = isWhitelisted(msg.sender);
        (bool _isWhitelistedTo, string memory _isoTo) = isWhitelisted(_to);

        require (_isWhitelistedFrom && _isWhitelistedTo, "Sender or recipient is not whitelisted");
        require(regulatorService.canTransfer(msg.sender, _isoFrom, _to, _isoTo, _amount), "Regulator service is not allowed to transfer");

        return super.transfer(_to, _amount);
    }

    function transferFrom(address _from, address _to, uint _amount) public onlyUnlocked returns(bool) {
        (bool _isWhitelistedFrom, string memory _isoFrom) = isWhitelisted(_from);
        (bool _isWhitelistedTo, string memory _isoTo) = isWhitelisted(_to);

        require (_isWhitelistedFrom && _isWhitelistedTo, "Sender or recipient is not whitelisted");
        require(regulatorService.canTransfer(_from, _isoFrom, _to, _isoTo, _amount), "Regulator service is not allowed to make the transfer");

        return super.transferFrom(_from, _to, _amount);
    }

    function mint(address _for, uint _amount) public onlyMintablePermission {
        (bool _isWhitelisted, string memory _iso) = isWhitelisted(_for);
        require(_isWhitelisted, "Recipient is not whitelisted");
        require(regulatorService.canMint(_for, _iso, _amount), "Regulator service is not allowed this minting");

        _mint(_for, _amount);
    }

    function recoveryTokens(address _from, address _to) public onlyRecoveryTokensPermission {
        require(regulatorService.canRecoveryTokens(_from, _to), "Regulator service is not allowed this token recovery");

        (bool _isWhitelisted, string memory _iso) = isWhitelisted(_from);
        require(_isWhitelisted, "Account from is not whitelisted");

        uint balance = balanceOf(_from);

        removeWhitelisted(_from);
        addWhitelisted(_to, _iso);

        _burn(_from, balance);
        mint(_to, balance);

        emit TokensRecovered(_from, _to, balance);
    }
}
```

**Comment by chicxurug** [comment]
It looks like the Solidity grammar is not complete (if the sol file is valid). Unfortunately, I just used an external grammar file (.g). It should be adjusted probably, try to get in connection with its developer.
